server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead_course
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true



